# Generated by Django 3.1.7 on 2021-04-01 13:49

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default=account.models.createCode, max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Invintation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default=account.models.createCode, max_length=6, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='my_invintations',
            field=models.ManyToManyField(blank=True, default=[], related_name='creator_id', to='account.Invintation'),
        ),
        migrations.AddField(
            model_name='user',
            name='used_invintation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.invintation'),
        ),
    ]
