# Generated by Django 3.1.7 on 2021-04-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210401_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='used_invintation',
        ),
    ]
