# Generated by Django 3.1.7 on 2021-04-25 10:39

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invintation',
            name='value',
            field=models.CharField(blank=True, default=account.models.createCodeDigits6, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, default=account.models.createCodeDigits6, max_length=6, unique=True),
        ),
    ]
