# Generated by Django 3.1.7 on 2021-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210401_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_invintations',
            field=models.ManyToManyField(blank=True, default=[], related_name='creator_user', to='account.Invintation'),
        ),
    ]
