# Generated by Django 3.1.7 on 2021-04-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210401_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='invintation',
            name='used',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
