# Generated by Django 3.1.7 on 2022-02-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220223_2148'),
    ]

    operations = [
        migrations.RunSQL('''
            update account_invintation as ai
            set creator_id = (
            select user_id
            from account_user_my_invintations
            where invintation_id = ai.id)
        ''')
    ]
