# Generated by Django 3.1.7 on 2022-02-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_move_invintations_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='my_invintations',
        ),
    ]
