# Generated by Django 3.1.7 on 2021-04-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210401_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='code',
            new_name='phone_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='confirmed',
            new_name='phone_confirmed',
        ),
    ]
