# Generated by Django 3.1.7 on 2021-04-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210401_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='device_token',
            field=models.TextField(default=''),
        ),
    ]
