# Generated by Django 3.1.7 on 2021-04-03 12:43

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210401_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationToReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=60)),
                ('code', models.CharField(blank=True, default=account.models.createCode, max_length=6, unique=True)),
                ('user_code', models.CharField(blank=True, default=account.models.createCode, max_length=6, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
