# Generated by Django 3.1.7 on 2022-06-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220601_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.TextField(choices=[('visit.duration', 'visit duration'), ('visit.is_free', 'visit is free')])),
                ('comparator', models.TextField(choices=[('==', '=='), ('>=', '>='), ('<=', '<='), ('>', '>'), ('<', '<')])),
                ('value', models.TextField()),
                ('scheduled_notify', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='account.schedulernotify')),
            ],
        ),
    ]
