# Generated by Django 3.1.7 on 2022-06-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
