# Generated by Django 3.1.7 on 2023-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20220410_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='free_reason',
            field=models.CharField(choices=[('CNT', 'По количеству посещений'), ('INV', 'Приглашение')], max_length=255, null=True, verbose_name='Причина бесплатного визита'),
        ),
    ]
