# Generated by Django 3.1.7 on 2025-08-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_visit_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='Подтвержденное?'),
        ),
    ]
