# Generated by Django 3.1.7 on 2021-04-11 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mobile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=mobile.models.now, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
