# Generated by Django 3.1.7 on 2021-03-30 04:59

from django.db import migrations, models
import mobile.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(blank=True, default=mobile.models.now, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
