# Generated by Django 3.1.7 on 2021-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_visit_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
