# Generated by Django 3.1.7 on 2021-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_visit_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
