# Generated by Django 3.1.7 on 2022-04-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobile', '0004_visit_free_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'визит', 'verbose_name_plural': 'Визиты'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='free_reason',
            field=models.CharField(choices=[('CNT', 'Count'), ('INV', 'Invite')], max_length=255, null=True, verbose_name='Причина бесплатного визита'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='staff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits_staff', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
