# Generated by Django 3.1.7 on 2023-01-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobanner',
            options={'verbose_name': 'Промо баннер', 'verbose_name_plural': 'Промо баннеры'},
        ),
    ]
