# Generated by Django 3.1.7 on 2021-04-24 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_visits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('to_users', models.ManyToManyField(blank=True, default=[], related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
