# Generated by Django 3.1.7 on 2022-02-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220223_2114'),
        ('mobile', '0002_auto_20220223_2104'),
    ]

    operations = [
        migrations.RunSQL('''
            update account_child as ac
            set my_parent_id = (
            select user_id
            from account_user_children
            where child_id = ac.id)
        ''', reverse_sql=''),
        migrations.RunSQL('''
                update mobile_visit as visit
                set user_id = (
                select user_id
                from account_user_visits
                where account_user_visits.visit_id = visit.id)

        ''', reverse_sql=''),
    ]
