# Generated by Django 3.1.7 on 2022-03-26 07:35

import apps.account.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220319_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_token',
            field=models.TextField(default='', verbose_name='токен устройства для отправки пушей'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_code',
            field=models.CharField(blank=True, default=apps.account.models.createCodeDigits6, max_length=6, unique=True, verbose_name='проверочный код телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='телефон подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='used_invintation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.invintation', verbose_name='использованный код приглашения'),
        ),
    ]
