# Generated by Django 3.1.7 on 2022-04-10 14:37

from django.db import migrations, models
import apps.mobile.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220326_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'ребенок', 'verbose_name_plural': 'Дети'},
        ),
        migrations.AlterModelOptions(
            name='invintation',
            options={'verbose_name': 'пригласительный купон', 'verbose_name_plural': 'Пригласительные купоны'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='tmphash',
            name='created_at',
            field=models.DateTimeField(default=apps.mobile.models.now),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
