# Generated by Django 3.1.7 on 2023-01-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220608_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_change_email', 'Show email field'), ('can_change_password', 'Show password field'), ('can_see_events', 'Show events sectinos'), ('can_change_permissions', 'Show permissions'))},
        ),
    ]
