# Generated by Django 3.1.7 on 2023-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20230129_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'Условие', 'verbose_name_plural': 'Условия'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Пуш', 'verbose_name_plural': 'Пуши'},
        ),
        migrations.AlterModelOptions(
            name='schedulernotify',
            options={'verbose_name': 'Периодический пуш', 'verbose_name_plural': 'Периодические пуши'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_change_email', 'Show email field'), ('can_change_password', 'Show password field'), ('can_see_events', 'Show events sectinos'), ('can_change_permissions', 'Show permissions')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(verbose_name='Возраст (вводится в приложении)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения (заполняется сотрудником)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.TextField(choices=[('F', 'Женский'), ('M', 'Мужской')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='comparator',
            field=models.TextField(choices=[('==', '=='), ('>=', '>='), ('<=', '<='), ('>', '>'), ('<', '<')], verbose_name='Тип сравнения'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='variable',
            field=models.TextField(choices=[('visit.duration', 'Продолжительность посещения'), ('visit.is_free', 'Визит бесплатный?')], verbose_name='Переменная'),
        ),
        migrations.AlterField(
            model_name='schedulernotify',
            name='minute_offset',
            field=models.IntegerField(default=0, verbose_name='Через сколько минут после события срабатывает'),
        ),
        migrations.AlterField(
            model_name='schedulernotify',
            name='trigger',
            field=models.TextField(choices=[('start', 'Начало посещения'), ('end', 'Конец посещение')], verbose_name='Событие активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
