# Generated by Django 3.1.7 on 2024-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20230129_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_for_sms_notifications',
            field=models.BooleanField(default=True, verbose_name='Согласие смс уведомления'),
        ),
        migrations.AddField(
            model_name='user',
            name='agree_for_video',
            field=models.BooleanField(default=True, verbose_name='Согласие на видеозапись'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_mobile_app_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего визита в приложение'),
        ),
    ]
