# Generated by Django 3.1.7 on 2024-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20241005_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_from_staff',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий сотрудника'),
        ),
    ]
