# Generated by Django 3.1.7 on 2026-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_user_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_admin_activity_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего действия в админке'),
        ),
    ]
