# Generated by Django 3.1.7 on 2026-02-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_last_admin_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source_platform',
            field=models.CharField(choices=[('mobile_application', 'Мобальное приложение'), ('admin_site', 'Админка'), ('telegram_bot', 'Телеграм бот')], default='admin_site', max_length=255, verbose_name='Платформа источник'),
        ),
    ]
