# Generated by Django 3.1.7 on 2026-02-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_user_source_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_telegram_bot_visit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего визита в телеграм бот'),
        ),
    ]
